test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------	

		args.OIDC_name="Outline"
		args.OIDC_secret="secret"
		args.OIDC_callback="domain.tld/callback"