test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------	

		args.name = "Outline"
		args.secret = "secret"
		args.callback = "domain.tld/callback"