# LDAP connector + Yunohost setup + staticClient as per manifest.json
issuer: https://__DOMAIN__/__PATH_URL__
storage:
  type: sqlite3
  config:
    file: dex.db
web:
  http: 127.0.0.1:__PORT__

connectors:
- type: ldap
  name: OpenLDAP
  id: ldap
  config:
    host: localhost:389

    # No TLS for this setup.
    insecureNoSSL: true
    insecureSkipVerify: true

    usernamePrompt: Username

    userSearch:
      baseDN: ou=users,dc=yunohost,dc=org
      filter: "(objectClass=InetOrgPerson)"
      username: uid
      idAttr: uid
      emailAttr: mail
      nameAttr: displayName

    groupSearch:
      baseDN: ou=groups,dc=yunohost,dc=org
      filter: "(objectClass=posixGroup)"

      userMatchers:
      - userAttr: uid
        groupAttr: memberUid

      nameAttr: cn

# Unfortunately the api is too complex to be used here
# As a consequence we have to setup client as staticClient, which means we will need one Dex instance per client app
staticClients:
- id: __OIDC_NAME__
  redirectURIs:
  - '__OIDC_CALLBACK__'
  name: '__OIDC_NAME__'
  secret: __OIDC_SECRET__